### PR TITLE
add support for python3, add close messages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by laulaz** [comment]
@marclava thanks for the work !  :pray:
Sorry for the late reply, I didn't see this PR in all the Github noise :zany_face:

I see that :
 - an upgrade step is missing for the new `image_quality` field
 - we should remove `includeDependencies` for Plone 6

I can take care of that.

Any other thoughts before testing & merging ?

**Comment by ghost** [comment]
@laulaz, you're welcome! I ended managing a private fork on gitlab, and probably added changes. I initially wanted to fix the CI step, but it was too difficult (I believe in automation, but most CI systems are out of my each). So if you can take care of CI, I would appreciate. But If I'd like to propose more changes, would I really have to use the whole CI shebang (only for a few lines of code)?

**Comment by laulaz** [comment]
@marclava 
- [X] missing upgrade step added (for `image_quality`)
- [X] Github action added for tests instead of Travis (dead for OSS)
- [X] Robot tests fixed
- [X] doc / contributor / classifiers updated

**Comment by ghost** [comment]
@laulaz: Great! So tests are now working?

**Comment by laulaz** [comment]
@marclava yes they are 👍 
But only for Plone 6 / Python 3 for now ... didn't have the time to write the whole versions matrix / config files for Plone 5 & 6 / Python 2 & 3 yet.

**Comment by laulaz** [comment]
@marclava 
Current branch is tested on Python 3.x / Plone 5.2.x & Plone 6.0.x now 👍

**Pull request merged**
